# Lebronaire Config

# IOCP
[iocp]
hostname = "192.168.86.48"
port = 8092

# Arduino's
[arduino.mega1]
path = "/dev/tty.usbmodem146101"


[prosim]
# configXMLPath = "/Users/atridgedcosta/Documents/Projects/lebronaire/flight-control-system/packages/server/sample/atr-config.xml"
configXMLPath = "/Users/atridgedcosta/Desktop/config.xml"

[controls]
# Example
# arduino: Must match the name of an arduino above
# pin: Exact pin number on the arduino
# type(optional): guage / led
# inverted: tue / false


# Electric
#"APU switch Off" =                  { arduino = "mega1", pin = 8,   inverted = true }
#"APU switch Start" =                { arduino = "mega1", pin = 6,   inverted = true }
#"Ignition select Left" =            { arduino = "mega1", pin = 3,   inverted = true }
#"Ignition select Right" =           { arduino = "mega1", pin = 4,   inverted = true }
#"Battery switch On" =               { arduino = "mega1", pin = 43 }
#"Standby power switch Auto" =       { arduino = "mega1", pin = 27,  inverted = true }
#"Standby power switch Bat" =        { arduino = "mega1", pin = 28,  inverted = true }

# OVHD BUS Panel
"APU Low oil pressure" =            { arduino = "mega1", pin = 3,  type = "led" }
"Transfer bus OFF 1" =              { arduino = "mega1", pin = 11,  type = "led"  }
"Transfer bus OFF 2" =              { arduino = "mega1", pin = 7,  type = "led"  }
"Source OFF 1" =                    { arduino = "mega1", pin = 9,  type = "led"  }
"Source OFF 2" =                    { arduino = "mega1", pin = 5,  type = "led"  }
"APU GEN OFF BUS" =                 { arduino = "mega1", pin = 8,  type = "led" }

#"GEN BUS OFF 1" =                   { arduino = "mega1", pin = 999,  type = "led" }
#"GEN BUS OFF 2" =                   { arduino = "mega1", pin = 999,  type = "led" }
# "GEN 1 On" =                        { arduino = "mega1", pin = 14,   inverted = true }
# "GEN 1 Off" =                       { arduino = "mega1", pin = 10,   inverted = true }
# "GEN 2 On" =                        { arduino = "mega1", pin = 18,   inverted = true }
# "GEN 2 Off" =                       { arduino = "mega1", pin = 21,   inverted = true }
"APU GEN 1 On" =                    { arduino = "mega1", pin = 12,   inverted = true }
"APU GEN 1 Off" =                   { arduino = "mega1", pin = 13,  inverted = true }
"APU GEN 2 On" =                    { arduino = "mega1", pin = 19,  inverted = true }
"APU GEN 2 Off" =                   { arduino = "mega1", pin = 17,  inverted = true }
"Bus transfer switch Auto" =        { arduino = "mega1", pin = 20 }
"APU" =                             { arduino = "mega1", pin = 44, type = "gauge" }
